Q. Write a function so that the columns of the output matrix are powers of the input  vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False,
the i-th output column is the input vector raised element-wise to the power of N - i - 1. 

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde. 

In [2]:
import numpy as np

def vander_mat(x,N):
    y=np.matrix([x**(N-1-i) for i in range(N)])
    y=y.T
    print("Output Martix:")
    print(y)
 
lst=[]  
n=int(input("Enter number of elements you want to enter in array: ")) 
for i in range(0, n): 
    e = int(input()) 
    lst.append(e)

x=np.asarray(lst)
N=int (input("Enter the value of vector N :"))

vander_mat(x,N)

Enter number of elements you want to enter in array: 4
1
2
3
4
Enter the value of vector N :4
Output Martix:
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


Q. Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given 
sequence is defined as follows:  
The moving average sequence has n-k+1 elements as shown below.  
The moving averages with k=4 of a ten-value sequence (n=10) is shown below  
i      1  2  3  4  5  6  7  8  9 10 
===== == == == == == == == == == == 
Input 10 20 30 40 50 60 70 80 90 100  
y1      25 = (10+20+30+40)/4  
y2      35 = (20+30+40+50)/4  
y3      45 = (30+40+50+60)/4  
y4      55 = (40+50+60+70)/4 
y5      65 = (50+60+70+80)/4 
y6      75 = (60+70+80+90)/4 
y7      85 = (70+80+90+100)/4   
Thus, the moving average sequence has n-k+1=10-4+1=7 values. 

Question: Write a function to find moving average in an array over a window:
          Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 

In [3]:
import numpy as np

def mov_avg(arr,k):
    n=len(arr)
    num=n-k+1 

    for i in np.arange(num):
        for j in arr:
            u=arr[i:i+k]
            avg=sum(u)/k
        print("Y(",i+1,"):","%.2f"%avg)
arr=np.asarray([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]) 
k=3  
mov_avg(arr,k) 
    


Y( 1 ): 5.00
Y( 2 ): 4.67
Y( 3 ): 5.67
Y( 4 ): 6.67
Y( 5 ): 9.67
Y( 6 ): 28.67
Y( 7 ): 49.33
Y( 8 ): 72.67
Y( 9 ): 84.00
Y( 10 ): 93.33
Y( 11 ): 116.33
